a = input("vnesite prvo število: ")
b = input("vnesite drugo število: ")
c = input("vnesite drugo število: ")
print(a + " " + str(type(a)))
print(b + " " + str(type(b)))
print(c + " " + str(type(c)))
print(a == b and c <= a)
